# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='childcid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='childcidname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dealerid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='marketprice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
